name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH for Backend
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BACKEND_EC2_SSH_KEY }}

      - name: Deploy Backend
        env:
          EC2_HOST: ${{ secrets.BACKEND_EC2_HOST }}
          EC2_USER: ${{ secrets.BACKEND_EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            cd AvenCRM
            git pull --rebase origin main

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd backend
            pnpm install --frozen-lockfile
            pnpx prisma generate
            pnpm build
            pm2 restart all
          EOF

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH for Frontend
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FRONTEND_EC2_SSH_KEY }}

      - name: Deploy Frontend
        env:
          EC2_HOST: ${{ secrets.FRONTEND_EC2_HOST }}
          EC2_USER: ${{ secrets.FRONTEND_EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            cd AvenCRM
            git pull --rebase origin main

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd frontend
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart all
          EOF
