name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Backend
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BACKEND_EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        env:
          EC2_HOST: ${{ secrets.BACKEND_EC2_HOST }}
          EC2_USER: ${{ secrets.BACKEND_EC2_USER }}
        run: |
          # Add EC2 host to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

          # SSH into EC2 and run deployment commands
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            cd AvenCRM
            
            # Pull latest changes
            git pull origin main
            
            # Backend deployment
            cd backend
            /home/ubuntu/.nvm/versions/node/v22.13.1/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v22.13.1/bin/pnpm build
            /home/ubuntu/.nvm/versions/node/v22.13.1/bin/pm2 restart all
          EOF

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Frontend
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FRONTEND_EC2_SSH_KEY }}

      - name: Deploy Frontend to EC2
        env:
          EC2_HOST: ${{ secrets.FRONTEND_EC2_HOST }}
          EC2_USER: ${{ secrets.FRONTEND_EC2_USER }}
        run: |
          # Add EC2 host to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

          # SSH into EC2 and run deployment commands
          ssh $EC2_USER@$EC2_HOST << 'EOF'
            cd AvenCRM
            
            # Pull latest changes
            git pull origin main
            
            # Frontend deployment
            cd frontend
            /home/ubuntu/.nvm/versions/node/v22.13.0/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v22.13.0/bin/pnpm build
            /home/ubuntu/.nvm/versions/node/v22.13.0/bin/pm2 restart all
          EOF
